/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdministrationGui;

import java.io.StringReader;

/**
 *
 * @author Grzesiek
 */
public class MapPanel extends javax.swing.JPanel {

    /**
     * Creates new form MapPanel
     */
    public MapPanel() {
        initComponents();
        StringReader in = new StringReader("<node id=\u005c"30376951\u005c" visible=\u005c"true\u005c" version=\u005c"6\u005c" changeset=\u005c"17360569\u005c" timestamp=\u005c"2013-08-15T15:06:53Z\u005c" user=\u005c"W\u0142adys\u0142aw Komorek\u005c" uid=\u005c"693154\u005c" lat=\u005c"50.0629329\u005c" lon=\u005c"19.9324157\u005c"/>");
        //MapParser interpreter = null;
        //interpreter.start();
  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
