/* Generated By:JavaCC: Do not edit this line. MapParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MapParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NODE = 52;
  /** RegularExpression Id. */
  int WORD = 53;
  /** RegularExpression Id. */
  int NUM = 54;
  /** RegularExpression Id. */
  int NID = 55;
  /** RegularExpression Id. */
  int NEND = 56;
  /** RegularExpression Id. */
  int LAT = 57;
  /** RegularExpression Id. */
  int LON = 58;
  /** RegularExpression Id. */
  int LNUM = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"=\"",
    "\"\\\"\"",
    "\"-\"",
    "\":\"",
    "\"\\u00a4\"",
    "\"\\u00a5\"",
    "\"\\u00a8\"",
    "\"\\u00a9\"",
    "\"\\u2014\"",
    "\"\\ufffd\"",
    "\"\\u02dd\"",
    "\"\\u013e\"",
    "\"\\u0104\"",
    "\"\\u0179\"",
    "\"\\u201a\"",
    "\"\\u0164\"",
    "\"\\u00ab\"",
    "\"\\u2020\"",
    "\"\\u0103\"",
    "\"\\u00e4\"",
    "\"\\u02d8\"",
    "\"\\u0155\"",
    "\"\\u0165\"",
    "\"\\u0139\"",
    "\"\\u0142\"",
    "\"\\u2021\"",
    "\"\\u2122\"",
    "\"\\u203a\"",
    "\"\\u2026\"",
    "\"\\u015f\"",
    "\"\\u201e\"",
    "\"\\u0105\"",
    "\"\\u0106\"",
    "\"\\u0107\"",
    "\"\\u0118\"",
    "\"\\u0119\"",
    "\"\\u0141\"",
    "\"\\u0143\"",
    "\"\\u0144\"",
    "\"\\u00d3\"",
    "\"\\u00f3\"",
    "\"\\u015a\"",
    "\"\\u015b\"",
    "\"\\u017a\"",
    "\"\\u017b\"",
    "\"\\u017c\"",
    "\".\"",
    "\"<node id\"",
    "<WORD>",
    "<NUM>",
    "<NID>",
    "\"/>\"",
    "\"lat=\"",
    "\"lon=\"",
    "<LNUM>",
  };

}
